# Generated by Django 5.2 on 2025-05-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='doing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
